### ISSUE TITLE
Error when sharing a link to a Norwegian only page on facebook

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1056]

**Comment by meols** [comment]
The issue is related to this page:   https://www.equinor.com/no/karriere/rekruttering-operasjonsgrupper.

**Comment by SvSven** [comment]
@fernandolucchesi @wenche I've updated the `getFullUrl` function to take locale into account, which should fix this issue. Have also taken the liberty of fixing the broken `og:url` for archived news, which wasn't being handled properly 😅

**Comment by wenche** [comment]
@SvSven  Works fine for the og:url, but the visual part for the news articles are still wrong
![Skjermbilde 2022-05-04 kl. 14.21.34.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/b6bf69e8-e1a6-4efb-a030-fdc0c3f94cf0)
![Skjermbilde 2022-05-04 kl. 14.08.53.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/97deb18a-3de5-4a46-aa33-ce90d0888847)

**Comment by wenche** [comment]
![Skjermbilde 2022-05-09 kl. 09.29.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/7ce3f599-5296-4890-9305-a0c61f6ee8f6)

Not available in all the environments yet, but I can see it in global-development :thumbsup:

**Comment by wenche** [comment]
@meols  and Jørgen: You should be able to test the issue you experienced now. I would have tested it like this:

1. Go to a Norwegian URL in preprod, like https://web-energyvision-preprod.radix.equinor.com/no/energi/hydrogen
2. Right click and view source
3. Search for og:url
4. Verify that /no is added to the URL (should look like this `<meta property="og:url" content="https://www.equinor.com/no/energi/hydrogen"/>`)

Facebook also have a [nifty little tool for debugging sharing URLs](https://developers.facebook.com/tools/debug/). It might not be available for you as you need to add a developer role to your personal Facebook account. But it looks like this with the hydrogen URL and you can see that it's working as expected

 ![Skjermbilde 2022-05-09 kl. 09.36.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/2a06cfbf-5b85-4670-8608-10d9dd378b1f)

**Comment by fernandolucchesi** [comment]
@meols @jojog007

**Comment by meols** [comment]
thanks @wenche :smile:
