### ISSUE TITLE
Horizontal scroll adds hidden cards in certain window sizes

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#1595]
![Screenshot 2023-04-17 at 15 23 55](https://user-images.githubusercontent.com/21845545/232497173-dc4511bc-b0ae-46d7-b66e-99a6f893bd2f.png)

**Comment by millianapia** [comment]
might have been fixed with dependency upgrade - will monitor, have not replicated the problem after upgrade

**Comment by millianapia** [comment]
@NickHaggerty1 @meols this is the bug that we discussed in #1418, can you verify that it works as intended?

**Comment by meols** [comment]
@millianapia - I still see issues as described in #1418. See new attachments ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/38567270-9d81-46c4-aaef-54c89a03abc4) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/d8eee58f-ae20-4664-acbc-97f3d75a7606)![iPhone13-1.jpeg](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/5e6e32a9-c8b3-458b-88c7-2e8256a723a8)![iPhone13-2.jpeg](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/aca84124-6b93-4d0c-b5a4-35deeb52304b)![iPhone13-3.jpeg](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/b9de3986-d1ec-4efe-8c6e-a51304a9ee46)s

**Comment by NickHaggerty1** [comment]
@millianapia @fernandolucchesi @meols Hey. I see the same issues as Mette (both in stage and on our live site) So I dont think the issue is solved. If it helps w can share screen? THis should not stop the deploy though as we are waiting for the new elements/video for tasks

**Comment by millianapia** [comment]
@NickHaggerty1 i replaced the old component with a new one, should not get this issue anymore, will take it through a new round of technical review, and then hopefully it will be gone for good :)

**Comment by fernandolucchesi** [comment]
@millianapia left some comments for you

**Comment by millianapia** [comment]
I took a different approach to this, ready to be reviewed @fernandolucchesi

**Comment by fernandolucchesi** [comment]
components still need a wrapper limiting the amount of the width it can grow: 
![Uploading image.png…]()

**Comment by millianapia** [comment]
@fernandolucchesi maybe just a simple
`  max-width: var(--iframe-maxWidth, var(--maxViewportWidth));
  margin: auto;` will do?

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi maybe just a simple ` max-width: var(--iframe-maxWidth, var(--maxViewportWidth)); margin: auto;` will do?

won't work due to the arrows.

so we have 2 different components and different UIs:

![image](https://user-images.githubusercontent.com/23337266/236295121-cfb0ccb3-13cb-4d41-a00d-bb4af4cd2e1a.png)

and: 

![image](https://user-images.githubusercontent.com/23337266/236295403-82e7b01e-b1b7-4678-b6e2-f427d79c66dc.png).


If you want to use the first one, you will need a Wrapper with a limiter on both sides of the screen, because the arrows to slide the component are outside of the component. So something like: `padding: var(--iframe-innerPadding, 0 var(--layout-paddingHorizontal-small));` will do. If you want to make the first component look like the second, then you need to extend Carousel API to accept a parameter that will display the button arrows like the second one, then you won't need to add "extra room" for the arrows

**Comment by fernandolucchesi** [comment]
My recommendation is to kill old design, and always go for:

![image](https://user-images.githubusercontent.com/23337266/236297252-e5193b54-5e95-47fa-8006-554bb1afd56c.png)

**Comment by millianapia** [comment]
i liked how it looked in your suggestion, so i think this is the way to go, feels good navigating on the phone ![Screenshot 2023-05-05 at 12 42 15](https://user-images.githubusercontent.com/21845545/236437498-d2a0e1de-a9c5-4540-9047-919efb5c8493.png)

**Comment by millianapia** [comment]
@fernandolucchesi any last comments before i move this forward?

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi any last comments before i move this forward?

I think it looks good! Just a reminder to cleanup some comments you left in the Carousel.tsx file.

**Comment by millianapia** [comment]
@meols @NickHaggerty1 the cards should behave correctly now, can you verify?

**Comment by millianapia** [comment]
@meols @NickHaggerty1

**Comment by meols** [comment]
@millianapia - let me know if you want to have a screen sharing session on this.

**Comment by millianapia** [comment]
@meols should be working 100% everywhere now, one final verify from you?

**Comment by millianapia** [comment]
@meols it is due to it is a multiple event component, and a single promotion component, so they look different. I have now pushed a fix for the width of when one only have one event for multiple event component, with the removal of featureflags for this:)
