### ISSUE TITLE
Adjustments to Full width image component 

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1756]
Currently the Full width image component is defined as 10:3. We would like on occasion to use more height so would like to add option on images.

1. Narrow (10/3) - Current. Default 
2. 2/1 - New option

Would it be possible to display crop as 2/1 on mobile? Currently the wide image looks very narrow on a mobile especially when next to a teaser component

**Comment by fernandolucchesi** [comment]
@NickHaggerty1 what about tablets (medium sized screens)?

**Comment by padms** [comment]
@meols We can run a script to fix this for existing components. For newly created ones, the default option is selected.

**Comment by meols** [comment]
@padms - when I add a full width image I see nothing selected for aspect ratio and I need to click and make a choice.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWxQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9b2ca272363e31d461505e98cf3e25ad920b4094/aspect-ratio.mp4)

**Comment by padms** [comment]
@meols Ran a script which set aspectRatio of all fullWidthImages to 10:3

**Comment by padms** [comment]
> @padms - when I add a full width image I see nothing selected for aspect ratio and I need to click and make a choice.
Uploaded asset

@meols Fixed now!

**Comment by meols** [comment]
@padms - I still don't see 10:3 default/pre-selected
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazllIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a3c1a81d2cfa0f7f0130514aa71244c4840c286e/aspect%20ratio%2001-09.mp4)

**Comment by padms** [comment]
@meols There was an issue with the pipeline, so it didn't get deployed. Now its deployed and fixed.

**Comment by meols** [comment]
Thanks @padms - this is approved

**Comment by fernandolucchesi** [comment]
Waiting for #1626
