### ISSUE TITLE
Occurences of http

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2496]

**Comment by BorghildSelle** [comment]
Task for :
Add warning on external link sanity component about using http or uppercase. should have https and lowercase
is done in connected PR #2503

**Comment by padms** [comment]
@meols We have added a check for external link field, if http:// is used, to avoid additional redirect to https://

**Comment by meols** [comment]
Thanks @padms - I like this way of solving it, but currently there are some issues
- For external links in the text block component the warning is yellow (I like the red warning :wink:)
- It looks like there is a check for external link even if it is the internal link that is in use, so internal links give a red warning related to external link
- When I change to https and lower case I still get a red warning
<img width="1407" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEg2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d8d1c14982932a5fab30e669dc39649c9c3bb7a/image.png" alt="image.png" />

<img width="985" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFA2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7764aaf25f97592a92f409f74b98f1e88d402b98/image.png" alt="image.png" />

<img width="1096" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFQ2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b33c7c67bcc3ab5ce6f767cf774bc393ef272588/image.png" alt="image.png" />

**Comment by padms** [comment]
@meols This is ready for a second review now.

- Allowed a url to be case sensitive only for equinor.com and other satellite site urls, if its external it allows ( in cases where it might be case sensitive)
- Fixed the warning to error
- Fixed the bug with validation.

**Comment by meols** [comment]
Thanks @padms - is it possible to give some hints to editors on what they need to fix?
In this case/screenshot it actually took me a while to see that there were capital letters included in the url (which I didn't understand from the error message)
<img width="1579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN05FQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2a36b9616c3e99beef13fa117ed002b5fa06f52/image.png" alt="image.png" />

Not sure what you mean in the first bullet. Can or can't an external url (not equinor.com or satellite sites) have capital letters in the url for external link.

**Comment by meols** [comment]
@padms - also an additional question to confirm - will doing this change mean that we will have to manually rewrite the urls that currently are http or including capital letters to be able to edit and republish a page?

**Comment by padms** [comment]
@meols We have a script that changes all the urls or( values ) that start with http: and replace it with https:// , no manual editing needed.

**Comment by meols** [comment]
@padms - the script from http to https I understand. But when it comes to uppercase and lowercase letters in urls, I am more hesitant if we should change it and wonder what will happen in the future (after implementing this) - both for existing external urls and new ones we add that are copied from their "original place" and used containing both uppercase and lowercase letters. Editors will probably use the links as they are received from stakeholders (copy/paste). Will these external urls then give an error message editors will struggle to understand and need to be manually edited to only contain lowercase letters - as I did for the last link on [this page](https://studiov3-global-development-equinor-web-sites-dev.c2.radix.equinor.com/global-development/desk/topicContent;007c9351-ca03-461e-9ac0-e118bf0385f9) (with real examples).
<img width="1411" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN05KQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eee56a3a0d9c9ffc1439695e9cd4c89ec7beaa24/image.png" alt="image.png" />

<img width="1435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JKQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf2d0ec7b9534f22d49ebce43506397a737a1f94/image.png" alt="image.png" />

**Comment by padms** [comment]
@meols This error related to magazine page with tags is fixed now.. 

What has been done: 

- Validation equinor.com ( and satellite site) urls are checked for lower case till the part before '?' , this would allow urls like 'https://www.equinor.com/magazine?tag=Our+energy+solutions' but not 'https://www.equinor.com/MAGAZINE?tag=Our+energy+solutions' also 'https://www.equinor.com/NY'
- Validation for non equinor.com urls, allows upper case letters.

**Comment by meols** [comment]
@padms - I'm still not sure about the upper/lower case issue. How critical is it to impplement that? As far as I remember it is related to a few short urls to avoid a redirect chain redirecting from uppercase to lowercase.
Could we rather just remove the redirect? Wouldn't any browser accept both lowercase and uppercase, so that we wouldn't need a redirect to handle it?

**Comment by padms** [comment]
@meols Both urls would be accepted with no doubt. Found this on google

> For SEO purposes, it's generally recommended to use lowercase letters in URLs because it avoids confusion and ensures consistency. Different capitalizations can lead to duplicate content issues, which might impact search engine rankings.

**Comment by padms** [comment]
@meols The error message "Equinor URLs should contain lower case letter only" appears for all equinor.com and satellite sites urls when the contain uppercase letters 
<img width="859" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1JkQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7736bbcd0629116dfff98f204c6ce9fb29f52ad5/image.png" alt="image.png" />

Urls like "https://www.equinor.com/magazine?tag=Our+energy+solutions" is allowed, as upper case letter after "?" is allowed and no redirect happens in such case. 

Other websites like "docmap.equinor.com" are treated as external websites and uppercase validation is not done.

**Comment by meols** [comment]
Thanks @padms - if you recommend to do this it's fine with me. One question to the error message where we get two messages for one error (http); could we remove the first one - "Does not match...." An editor (me included) wouldn't know what that one means.
<img width="967" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3hlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4566434588f78485a9e55cd006d62d3cff7fccf5/image.png" alt="image.png" />

**Comment by padms** [comment]
@meols I gave a fix to remove the extra error which is another way of saying "http is not allowed" :P

**Comment by meols** [comment]
Thanks @padms - approved :thumbsup:
